# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c702fa9d-76a2-4799-8889-643dd4d722bc";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/CAF5-7462";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/mnt/SSD1TB" = {
    device = "/dev/disk/by-uuid/69881c1d-7065-43f7-beef-9ecc060c6010";
    fsType = "ext4";
    options = ["nofail"];
  };
  fileSystems."/mnt/HDD1TB" = {
    device = "/dev/disk/by-uuid/925f418a-3cb8-431c-a5df-d82919c1d22d";
    fsType = "ext4";
    options = ["nofail"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/88c4ca5b-fccc-4a61-b1e5-1be235fee85b";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
